Book model crud
obniavko/book-reader-app pull request #1
Opened 2023-10-13 14:52 UTC by obniavko

2023-10-29 14:45 UTC, loqimean requested changes

2023-10-29 14:45 UTC, loqimean commented on Gemfile
> +end
де нова строка?

2023-10-29 14:45 UTC, loqimean commented on app/assets/stylesheets/application.tailwind.css
> +    @apply text-gray-900 bg-gradient-to-r from-lime-200 via-lime-400 to-lime-500 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-lime-300 dark:focus:ring-lime-800 font-medium round
кнопки в окремому файлі

2023-10-29 14:45 UTC, loqimean commented on app/assets/stylesheets/application.tailwind.css
> +  }
всьо інше в base.css

2023-10-29 14:45 UTC, loqimean commented on app/models/book.rb
> +  scope :ordered, -> { order(:title) }
скоуп йде зазвичай знизу

2023-10-29 14:45 UTC, loqimean commented on app/views/books/_book.json.jbuilder
а тобі це точно треба?

2023-10-29 14:45 UTC, loqimean commented on app/views/books/_form.html.erb
> +  <%= simple_form_for @book, defaults: { input_html: { class: "form" } } do |f| %>
а куда ти форму направляєш ? я не бачу передавання шляху

2023-10-29 14:45 UTC, loqimean commented on app/views/books/index.json.jbuilder
тобі це треба?))

2023-10-29 14:45 UTC, loqimean commented on app/views/books/show.json.jbuilder
знову те ж питання

2023-10-29 14:45 UTC, loqimean commented on app/views/shared/_footer.html.erb
> +    © 2023 Copyright
а якщо зараз 2024-ий рік?))

2023-10-29 14:45 UTC, loqimean commented on config/routes.rb
> +  resources :books
а де рут шлях?))

2023-10-29 14:45 UTC, loqimean commented on db/migrate/20231012202614_create_books.rb
> +      t.text :description, null: false
чому ісбн може бути відсутній, а дескріпшен ну полюбе має бути?))

2023-10-29 14:45 UTC, loqimean commented on lib/templates/erb/scaffold/_form.html.erb
що це за файл?)

2023-10-29 14:45 UTC, loqimean commented on spec/models/book_spec.rb
> +  it { is_expected.not_to allow_value("").for(:description) }
ну пуста строка не означає, що я не можу створити ісбн з символом `%` всередині

2023-10-29 14:45 UTC, loqimean commented on spec/models/book_spec.rb
> +    it { should validate_uniqueness_of(:isbn).case_insensitive }
шуд устарілий синтаксис

2023-10-29 14:45 UTC, loqimean commented on spec/requests/books_spec.rb
> +      expect(response).to be_successful
перевіряй, чи рендериться хоч якийсь рекорд

2023-10-29 14:45 UTC, loqimean commented on spec/requests/books_spec.rb
> +      expect(response).to be_successful
і на інших пейджах, де має рендеритися - теж

2023-10-29 14:45 UTC, loqimean commented on spec/requests/books_spec.rb
> +        expect(response).to redirect_to(book_path(Book.last))
тестуй на просто редірект, брати отсанній рекорд така собі ідея

2023-10-29 14:45 UTC, loqimean commented on spec/requests/books_spec.rb
> +        expect(response).to redirect_to(book_path(Book.last))
флеш теж не бачу тестування)

2023-10-29 14:45 UTC, loqimean commented on spec/requests/books_spec.rb
> +        expect(response).to redirect_to(book_path(Book.last))
і в інших місцях теж

2023-10-29 16:28 UTC, obniavko commented on Gemfile
> +end
Fixed.

2023-10-29 16:28 UTC, obniavko commented on lib/templates/erb/scaffold/_form.html.erb
Fixed.

2023-10-29 16:28 UTC, obniavko commented on app/views/books/index.json.jbuilder
Fixed.

2023-10-29 16:28 UTC, obniavko commented on app/views/books/show.json.jbuilder
Fixed.

2023-10-29 16:28 UTC, obniavko commented on config/routes.rb
> +  resources :books
Fixed.

2023-10-29 17:00 UTC, obniavko commented on app/models/book.rb
> +  scope :ordered, -> { order(:title) }
Fixed.

2023-10-29 17:00 UTC, obniavko commented on app/views/books/_book.json.jbuilder
Fixed.

2023-10-29 18:12 UTC, obniavko commented on app/views/shared/_footer.html.erb
> +    © 2023 Copyright
Fixed.

2023-10-30 15:06 UTC, obniavko commented on spec/models/book_spec.rb
> +    it { should validate_uniqueness_of(:isbn).case_insensitive }
Fixed.

2023-10-30 16:36 UTC, obniavko commented on app/assets/stylesheets/application.tailwind.css
> +    @apply text-gray-900 bg-gradient-to-r from-lime-200 via-lime-400 to-lime-500 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-lime-300 dark:focus:ring-lime-800 font-medium round
Fixed.

2023-10-30 16:37 UTC, obniavko commented on app/assets/stylesheets/application.tailwind.css
> +  }
Fixed.

2023-10-30 21:23 UTC, obniavko commented on spec/models/book_spec.rb
> +  it { is_expected.not_to allow_value("").for(:description) }
Fixed.

2023-10-30 21:23 UTC, obniavko commented on spec/requests/books_spec.rb
> +      expect(response).to be_successful
Fixed.

2023-10-30 21:24 UTC, obniavko commented on spec/requests/books_spec.rb
> +        expect(response).to redirect_to(book_path(Book.last))
Fixed.

2023-10-31 12:35 UTC, obniavko commented on app/views/books/_form.html.erb
> +  <%= simple_form_for @book, defaults: { input_html: { class: "form" } } do |f| %>
Fixed.

2023-11-02 08:14 UTC, loqimean requested changes

2023-11-02 08:14 UTC, loqimean commented on app/assets/stylesheets/application.tailwind.css
> +
це має бути під основним імпортом

2023-11-02 08:14 UTC, loqimean commented on app/models/book.rb
> +  validates :isbn, uniqueness: true, format: { with: /\A\d[\d-]*\d\z/,
тобі точно треба такий месидж, а не дефолтний?

2023-11-02 08:14 UTC, loqimean commented on db/migrate/20231012202614_create_books.rb
> +      t.string :isbn
а він не має бути завжди присутній?

2023-11-02 08:14 UTC, loqimean commented on spec/models/book_spec.rb
> +  it { is_expected.to validate_length_of(:title).is_at_most(150) }
обʼєднай, а також наступні такі теж

2023-11-02 08:14 UTC, loqimean commented on spec/models/book_spec.rb
> +  it { is_expected.not_to allow_value("a" * 1001).for(:description) }
в цих тестах нема сенсу, бо чуть вище, шуда матчерс, робить те ж саме

2023-11-02 08:14 UTC, loqimean commented on spec/models/book_spec.rb
> +    subject { FactoryBot.create(:book) }
а це навіщо?)

2023-11-02 09:24 UTC, obniavko commented on spec/models/book_spec.rb
> +    subject { FactoryBot.create(:book) }
Fixed.

2023-11-02 09:24 UTC, obniavko commented on spec/models/book_spec.rb
> +  it { is_expected.not_to allow_value("a" * 1001).for(:description) }
Fixed.

2023-11-02 09:24 UTC, obniavko commented on spec/models/book_spec.rb
> +  it { is_expected.to validate_length_of(:title).is_at_most(150) }
Fixed.

2023-11-02 09:27 UTC, obniavko commented on db/migrate/20231012202614_create_books.rb
> +      t.string :isbn
Fixed.

2023-11-02 09:27 UTC, obniavko commented on app/models/book.rb
> +  validates :isbn, uniqueness: true, format: { with: /\A\d[\d-]*\d\z/,
Fixed.

2023-11-02 09:40 UTC, obniavko commented on app/assets/stylesheets/application.tailwind.css
> +
Fixed.

2023-11-05 09:03 UTC, loqimean approved these changes

2023-11-05 11:23 UTC, loqimean approved these changes

2023-11-05 11:35 UTC, merged