Users authentication
obniavko/book-reader-app pull request #2
Opened 2023-11-06 19:00 UTC by obniavko

2023-11-06 21:25 UTC, loqimean requested changes

2023-11-06 21:25 UTC, loqimean commented on db/migrate/20231105121143_devise_create_users.rb
> +    create_table :users do |t|
бо потім прийдеться шукати і тд

2023-11-06 21:25 UTC, loqimean commented on spec/requests/users_spec.rb
> +  let!(:user) { FactoryBot.create(:user) }
клас фекторі_бот дефайниться по-замовчуванню, не тре передавати клас

2023-11-06 21:34 UTC, obniavko commented on app/views/shared/_header.html.erb
> +        <% end %>
Fixed.

2023-11-06 21:37 UTC, obniavko commented on spec/requests/users_spec.rb
> +  let!(:user) { FactoryBot.create(:user) }
Fixed.

2023-11-06 21:41 UTC, obniavko commented on db/migrate/20231105121143_devise_create_users.rb
> +    create_table :users do |t|
Fixed.

2023-11-06 22:02 UTC, obniavko commented on config/routes.rb
> +  devise_for :users
Fixed.

2023-11-07 08:04 UTC, obniavko commented on spec/requests/users_spec.rb
> +RSpec.describe UsersController, type: :request do
Fixed.

2023-11-08 08:41 UTC, loqimean approved these changes

2023-11-08 08:55 UTC, loqimean approved these changes

2023-11-08 08:56 UTC, merged