Active storage
obniavko/book-reader-app pull request #3
Opened 2023-11-14 21:55 UTC by obniavko

2023-11-15 18:39 UTC, loqimean requested changes

2023-11-15 18:39 UTC, loqimean commented on app/models/book.rb
> +  has_one_attached :content
а якщо я видалю книгу, що буде з цим контентом і кавером?

2023-11-15 18:39 UTC, loqimean commented on Gemfile
> +gem 'active_storage_validations'
це точно треба? вбудований функціонал такого не має?

2023-11-15 18:39 UTC, loqimean commented on spec/factories/attachments/Lorem_ipsum.pdf
а чому в фекторіс, а не в атачментс наприклад?

2023-11-15 18:39 UTC, loqimean commented on spec/factories/attachments/cover_placeholder.png
те ж питання

2023-11-15 18:39 UTC, loqimean commented on spec/factories/books.rb
> +    after(:create) do |book|
а якщо я захочу зробити просто білд?

2023-11-16 14:44 UTC, obniavko commented on Gemfile
> +gem 'active_storage_validations'
Без цього гему можна писати кастомні валідації через private methods, але хіба не доцільніше скористатися гемом?)

2023-11-16 15:44 UTC, obniavko commented on app/models/book.rb
> +  has_one_attached :content
Fixed.

2023-11-16 16:05 UTC, obniavko commented on spec/factories/attachments/Lorem_ipsum.pdf
Переніс в spec/fixtures

2023-11-16 16:05 UTC, obniavko commented on spec/factories/attachments/cover_placeholder.png
Переніс в spec/fixtures

2023-11-16 16:06 UTC, obniavko commented on spec/factories/books.rb
> +    after(:create) do |book|
Fixed.

2023-11-22 08:56 UTC, loqimean requested changes

2023-11-22 08:56 UTC, loqimean commented on Gemfile
> +gem 'active_storage_validations'
okay, най буде

2023-11-22 08:56 UTC, loqimean commented on spec/factories/books.rb
> +    content { Rack::Test::UploadedFile.new("spec/fixtures/Lorem_ipsum.pdf", "application/pdf") }
spec/support/files

2023-11-22 09:40 UTC, obniavko commented on spec/factories/books.rb
> +    content { Rack::Test::UploadedFile.new("spec/fixtures/Lorem_ipsum.pdf", "application/pdf") }
Fixed.

2023-11-22 12:30 UTC, loqimean approved these changes

2023-11-22 14:45 UTC, merged